ALTER TABLE user ADD COLUMN CREATIONDATE timestamp(23, 10);
ALTER TABLE user ADD COLUMN ACTIVATED boolean(1) NOT NULL;

UPDATE user
SET ACTIVATED = true, CREATIONDATE = '2010-01-01 00:00:00.000'
WHERE CREATIONDATE IS NULL;
